### ISSUE TITLE
IllegalState Exception

### ISSUE THREAD

**Issue by b-connect** [Ethras/flutter_simple_permissions#17]
```
E/MethodChannel#simple_permissions(31863): Failed to handle method call
E/MethodChannel#simple_permissions(31863): java.lang.IllegalStateException: Reply already submitted
E/MethodChannel#simple_permissions(31863):      at io.flutter.view.FlutterNativeView$1.reply(FlutterNativeView.java:146)
E/MethodChannel#simple_permissions(31863):      at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler$1.success(MethodChannel.java:194)
E/MethodChannel#simple_permissions(31863):      at com.ethras.simplepermissions.SimplePermissionsPlugin.onMethodCall(SimplePermissionsPlugin.java:55)
E/MethodChannel#simple_permissions(31863):      at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:191)
E/MethodChannel#simple_permissions(31863):      at io.flutter.view.FlutterNativeView.handlePlatformMessage(FlutterNativeView.java:136)
E/MethodChannel#simple_permissions(31863):      at android.os.MessageQueue.nativePollOnce(Native Method)
E/MethodChannel#simple_permissions(31863):      at android.os.MessageQueue.next(MessageQueue.java:375)
E/MethodChannel#simple_permissions(31863):      at android.os.Looper.loop(Looper.java:225)
E/MethodChannel#simple_permissions(31863):      at android.app.ActivityThread.main(ActivityThread.java:6589)
E/MethodChannel#simple_permissions(31863):      at java.lang.reflect.Method.invoke(Native Method)
E/MethodChannel#simple_permissions(31863):      at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
E/MethodChannel#simple_permissions(31863):      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767)
E/FlutterNativeView(31863): Uncaught exception in binary message listener
E/FlutterNativeView(31863): java.lang.IllegalStateException: Reply already submitted
E/FlutterNativeView(31863):     at io.flutter.view.FlutterNativeView$1.reply(FlutterNativeView.java:146)
E/FlutterNativeView(31863):     at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:209)
E/FlutterNativeView(31863):     at io.flutter.view.FlutterNativeView.handlePlatformMessage(FlutterNativeView.java:136)
E/FlutterNativeView(31863):     at android.os.MessageQueue.nativePollOnce(Native Method)
E/FlutterNativeView(31863):     at android.os.MessageQueue.next(MessageQueue.java:375)
E/FlutterNativeView(31863):     at android.os.Looper.loop(Looper.java:225)
E/FlutterNativeView(31863):     at android.app.ActivityThread.main(ActivityThread.java:6589)
E/FlutterNativeView(31863):     at java.lang.reflect.Method.invoke(Native Method)
E/FlutterNativeView(31863):     at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
E/FlutterNativeView(31863):     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767)
Restarted app in 3,083ms.
```

[✓] Flutter (Channel beta, v0.4.4, on Linux, locale en_US.UTF-8)
    • Flutter version 0.4.4 at /home/erik/projects/flutter/flutter
    • Framework revision f9bb4289e9 (6 weeks ago), 2018-05-11 21:44:54 -0700
    • Engine revision 06afdfe54e
    • Dart version 2.0.0-dev.54.0.flutter-46ab040e58

[✓] Android toolchain - develop for Android devices (Android SDK 27.0.3)
    • Android SDK at /home/erik/Android/Sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-27, build-tools 27.0.3
    • Java binary at: /home/erik/projects/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b01)
    • All Android licenses accepted.

[✓] Android Studio (version 3.1)
    • Android Studio at /home/erik/projects/android-studio
    • Flutter plugin version 23.1.2
    • Dart plugin version 173.4700
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b01)

[!] VS Code (version 1.24.1)
    • VS Code at /usr/share/code
    • Dart Code extension not installed; install from
      https://marketplace.visualstudio.com/items?itemName=Dart-Code.dart-code

[✓] Connected devices (1 available)
    • F5321 • BH901GN05Z • android-arm64 • Android 8.0.0 (API 26)

! Doctor found issues in 1 category.

**Comment by vikas10foodvite** [comment]
Is there any update on this? I am also getting the same error.

**Comment by ened** [comment]
Please could you submit a sample or code to reproduce this issue? Which permission was request etc..?

**Comment by vikas10foodvite** [comment]
Tried running the example of this library too. It was the same error yesterday. The code here I tried was from flutter_simple_permissions example code. Link:
https://pub.dartlang.org/packages/simple_permissions#-example-tab-

```
E/MethodChannel#simple_permissions(11445): Failed to handle method call
E/MethodChannel#simple_permissions(11445): java.lang.IllegalStateException: Reply already submitted
E/MethodChannel#simple_permissions(11445): 	at io.flutter.view.FlutterNativeView$1.reply(FlutterNativeView.java:146)
E/MethodChannel#simple_permissions(11445): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler$1.success(MethodChannel.java:194)
E/MethodChannel#simple_permissions(11445): 	at com.ethras.simplepermissions.SimplePermissionsPlugin.onMethodCall(SimplePermissionsPlugin.java:55)
E/MethodChannel#simple_permissions(11445): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:191)
E/MethodChannel#simple_permissions(11445): 	at io.flutter.view.FlutterNativeView.handlePlatformMessage(FlutterNativeView.java:136)
E/MethodChannel#simple_permissions(11445): 	at android.os.MessageQueue.nativePollOnce(Native Method)
E/MethodChannel#simple_permissions(11445): 	at android.os.MessageQueue.next(MessageQueue.java:323)
E/MethodChannel#simple_permissions(11445): 	at android.os.Looper.loop(Looper.java:136)
E/MethodChannel#simple_permissions(11445): 	at android.app.ActivityThread.main(ActivityThread.java:6165)
E/MethodChannel#simple_permissions(11445): 	at java.lang.reflect.Method.invoke(Native Method)
E/MethodChannel#simple_permissions(11445): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:888)
E/MethodChannel#simple_permissions(11445): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:778)
E/FlutterNativeView(11445): Uncaught exception in binary message listener
E/FlutterNativeView(11445): java.lang.IllegalStateException: Reply already submitted
E/FlutterNativeView(11445): 	at io.flutter.view.FlutterNativeView$1.reply(FlutterNativeView.java:146)
E/FlutterNativeView(11445): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:209)
E/FlutterNativeView(11445): 	at io.flutter.view.FlutterNativeView.handlePlatformMessage(FlutterNativeView.java:136)
E/FlutterNativeView(11445): 	at android.os.MessageQueue.nativePollOnce(Native Method)
E/FlutterNativeView(11445): 	at android.os.MessageQueue.next(MessageQueue.java:323)
E/FlutterNativeView(11445): 	at android.os.Looper.loop(Looper.java:136)
E/FlutterNativeView(11445): 	at android.app.ActivityThread.main(ActivityThread.java:6165)
E/FlutterNativeView(11445): 	at java.lang.reflect.Method.invoke(Native Method)
E/FlutterNativeView(11445): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:888)
E/FlutterNativeView(11445): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:778)
```

**Comment by ened** [comment]
Did you enable the developer setting "Don't keep activities"?

**Comment by vikas10foodvite** [comment]
@ened It was initially off. Just tried by turning it on. But still it's the same error.
