### ISSUE TITLE
Crash when request the permission on Android 

### ISSUE THREAD

**Issue by zinwalin** [Ethras/flutter_simple_permissions#40]
Flutter 0.8.2 • channel beta • https://github.com/flutter/flutter.git
Framework • revision 5ab9e70727 (2 weeks ago) • 2018-09-07 12:33:05 -0700
Engine • revision 58a1894a1c
Tools • Dart 2.1.0-dev.3.1.flutter-760a9690c2

  **simple_permissions: ^0.1.8**

I/SimplePermission(12040): Requesting permission : android.permission.RECORD_AUDIO
D/ViewRootImpl@8e099c6[MainActivity](12040): MSG_WINDOW_FOCUS_CHANGED 0
D/ViewRootImpl@8e099c6[MainActivity](12040): MSG_WINDOW_FOCUS_CHANGED 1
D/ViewRootImpl@8e099c6[MainActivity](12040): mHardwareRenderer.initializeIfNeeded()#2 mSurface={isValid=true 525000023552}
D/AndroidRuntime(12040): Shutting down VM
E/AndroidRuntime(12040): FATAL EXCEPTION: main
E/AndroidRuntime(12040): Process: xyz.mobile.potato, PID: 12040
E/AndroidRuntime(12040): java.lang.RuntimeException: Failure delivering result ResultInfo{who=@android:requestPermissions:, request=0, result=-1, data=Intent { act=android.content.pm.action.REQUEST_PERMISSIONS launchParam=MultiScreenLaunchParams { mDisplayId=0 mFlags=0 } (has extras) }} to activity {xyz.mobile.potato/xyz.mobile.potato.MainActivity}: java.lang.NullPointerException: Attempt to invoke interface method 'void io.flutter.plugin.common.MethodChannel$Result.success(java.lang.Object)' on a null object reference
E/AndroidRuntime(12040):        at android.app.ActivityThread.deliverResults(ActivityThread.java:4472)
E/AndroidRuntime(12040):        at android.app.ActivityThread.handleSendResult(ActivityThread.java:4515)
E/AndroidRuntime(12040):        at android.app.ActivityThread.-wrap22(ActivityThread.java)
E/AndroidRuntime(12040):        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1687)
E/AndroidRuntime(12040):        at android.os.Handler.dispatchMessage(Handler.java:102)
E/AndroidRuntime(12040):        at android.os.Looper.loop(Looper.java:154)
E/AndroidRuntime(12040):        at android.app.ActivityThread.main(ActivityThread.java:6682)
E/AndroidRuntime(12040):        at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(12040):        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1520)
E/AndroidRuntime(12040):        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1410)
E/AndroidRuntime(12040): Caused by: java.lang.NullPointerException: Attempt to invoke interface method 'void io.flutter.plugin.common.MethodChannel$Result.success(java.lang.Object)' on a null object reference
E/AndroidRuntime(12040):        at com.ly.permission.PermissionPlugin.onRequestPermissionsResult(PermissionPlugin.java:149)
E/AndroidRuntime(12040):        at io.flutter.app.FlutterPluginRegistry.onRequestPermissionsResult(FlutterPluginRegistry.java:191)
E/AndroidRuntime(12040):        at io.flutter.app.FlutterActivityDelegate.onRequestPermissionsResult(FlutterActivityDelegate.java:125)
E/AndroidRuntime(12040):        at io.flutter.app.FlutterActivity.onRequestPermissionsResult(FlutterActivity.java:133)
E/AndroidRuntime(12040):        at android.app.Activity.dispatchRequestPermissionsResult(Activity.java:7434)
E/AndroidRuntime(12040):        at android.app.Activity.dispatchActivityResult(Activity.java:7260)
E/AndroidRuntime(12040):        at android.app.ActivityThread.deliverResults(ActivityThread.java:4468)
E/AndroidRuntime(12040):        ... 9 more
Lost connection to device.

**Comment by ROTGP** [comment]
This is happening to me too... I've lost about 5 hours trying to resolve it (with no luck). It works fine on iOS, but as soon as I call requestPermission() on android it crashes. Appropriate keys are in my AndroidManifest.xml file.

`java.lang.RuntimeException: Failure delivering result ResultInfo{who=@android:requestPermissions:, request=0, result=-1, data=Intent { act=android.content.pm.action.REQUEST_PERMISSIONS (has extras) }} to activity {com.my.package/com.my.package.MainActivity}: java.lang.NullPointerException: Attempt to invoke interface method 'void io.flutter.plugin.common.MethodChannel$Result.success(java.lang.Object)' on a null object reference`

Any suggestions would be highly appreciated!

**Comment by ROTGP** [comment]
On further investigation, yes, it was related to https://github.com/babariviere/flutter_sms/issues/37 . I tried removing some other packages that I'm using and now everything works fine. Obviously this isn't a solution. Perhaps one package is overwriting another's callback? Any suggestions are welcome.

**Comment by fpiruzi** [comment]
same issue for me!
