### ISSUE TITLE
Missing plugin exception when calling checkPermission on iOS

### ISSUE THREAD

**Issue by riccardoratta** [Ethras/flutter_simple_permissions#50]
When I try to call on iOS this code
```dart
// check if I've already the permission
if (!(await SimplePermissions.checkPermission(p))) {
  // try to request the permission
  switch (await SimplePermissions.requestPermission(p)) {
    case PermissionStatus.restricted:
    case PermissionStatus.denied:
    case PermissionStatus.deniedNeverAsk:
    case PermissionStatus.notDetermined:
      return false;
    case PermissionStatus.authorized:
      return true;
  }
  // somthing wrong here
  return false;
}
```
I get this exception
```
MissingPluginException(No` implementation found for method checkPermission on channel simple_permissions)
#0      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:278:7)
<asynchronous suspension>
#1      SimplePermissions.checkPermission (package:simple_permissions/simple_permissions.dart:16:43)
<asynchronous suspension>
#2      _AddSpeakerState.permit (package:speech_convergence/views/add_speaker.dart:35:35)
<asynchronous suspension>
#3      _AddSpeakerState.build.<anonymous closure> (package:speech_convergence/views/add_speaker.dart:105:33)
<asynchronous suspension>
#4      _InkResponseState._handleTap (package:flutter/src/material/ink_well.dart:507:14)
#5      _InkResponseState.build.<anonymous closure> (package:flutter/src/material/ink_well.dart:562:30)
#6      GestureRecognizer.invokeCallback (package:flutter/src/gestures/recognizer.dart:102:24)
#7      TapGestureRecognizer._checkUp (package:flutter/src/gestu<…>
```
This is the podfile.lock (to check the package version, should be the lastest)
```
  simple_permissions:
    dependency: "direct main"
    description:
      name: simple_permissions
      url: "https://pub.dartlang.org"
    source: hosted
    version: "0.1.8"
```

**Comment by Shu-Ji** [comment]
I get the same exception with v0.1.8
